### PR TITLE
show layer dimension as a label inside shapes

### PR DESCRIPTION
**Pull request by amirshnll**
hi @paulgavrikov,
I appreciate you sharing this helpful library under an open source license.
Last night, I wanted to visualize my CNN and see all the resources, and your library is fantastic. However, visualkeras doesn't support layer dimension size; I have added this.

detail:
If you need to show layer dimantion you must set `legend=True` and `show_dimantion=True` in `layered_view` .

Changelog:
- edit layered.py and add show_dimantion param in this file
- duplicate `vgg16.py` file and rename this file to `show_dimantion.py` then added `show_dimantion` feature in this file
- Add some example image in `figures` folder
- edit `README.md` for userguide to use new feature

#27

### CODE REVIEW

**Comment by indramal** [comment]
Still, this is not added to this awesome library. I think it is better to add dimensions details in 3D boxes

**Comment by paulgavrikov** [comment]
Apologies, I rarely Have time for this project anymore and I haven’t used keras in ages … but I’ll take a look.

@amirshnll one thing I’ve noticed already is that you’ve misspelled “dimension” as dimantion

also there’s an older PR that does something similar I think (closed due to inactivity)

**Comment by amirshnll** [comment]
@paulgavrikov 

thank you i fixed "issue, merge request" title

**Comment by prabathbr** [comment]
> @paulgavrikov
> 
> thank you i fixed "issue, merge request" title

Thanks you very much for your fork. I just replaced "layered.py" from your fork in my installation and it works.

**Comment by amirshnll** [comment]
> > @paulgavrikov
> > thank you i fixed "issue, merge request" title
> 
> Thanks you very much for your fork. I just replaced "layered.py" from your fork in my installation and it works.

It's my pleasure @prabathbr

**Comment by indramal** [comment]
@amirshnll Link please

**Comment by amirshnll** [comment]
> @amirshnll Link please

first, you must install @paulgavrikov from `pip install visualkeras` command
second, go to installed path and replace `https://github.com/semnan-university-ai/visualkeras/blob/master/visualkeras/layered.py` file.

**Comment by Soontosh** [comment]
Hey ya'll. Thank you so much for your contribution and pull request - this is a really useful feature. I'll look through the code and test this on my machine. If everything works well, I'll merge this into the main branch. Sorry for the huge delay.

**Comment by Soontosh** [comment]
> Still, this is not added to this awesome library. I think it is better to add dimensions details in 3D boxes

@indramal Thanks for your input. I don't see this as being possible on layered view, as the 3D boxes will not allow for text to be clearly displayed on them, but it may be beneficial on the graph_view function. I'll try adding this to the grpah_view function and coauthor you for coming up with this idea.

**Comment by Soontosh** [comment]
Hey @indramal. I've made a few changes to your PR and opened a new PR with you as the coauthor and merged it. I'm closing this PR now.

**Pull request closed without merging**
